[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-prompt"
version = "0.0.33"
description = "Helper for your tty interactions"
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "colorama",
    "inquirerpy",
    "pip-tools",
    "pydantic",
    "pytest",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-prompt"

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "wexample_prompt*",
]

[tool.setuptools.package-dir]
"" = "."
